// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxbiwtltgjoqiygflfar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Yml3dGx0Z2pvcWl5Z2ZsZmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDcyMTgsImV4cCI6MjA2NjA4MzIxOH0.jhqo5pOo79YLpsBnkYjj3YYXnV4s4R_kYqSsv9NyFXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);